### ISSUE TITLE
"dub build --build=release"遇错

### ISSUE THREAD

**Issue by luckypoem** [nametoolong/flint#1]
root@RegalMusty-VM:~/flint# ls
LICENSE    README.zh_cn.md  flint.config         keytool
README.md  dub.json         flint.config_server  source
root@RegalMusty-VM:~/flint# dub build --build=release
Fetching memutils 0.4.9 (getting selected version)...
Fetching botan-math 1.0.3 (getting selected version)...
Fetching openssl 1.1.6+1.0.1g (getting selected version)...
Fetching botan 1.12.9 (getting selected version)...
Running pre-generate commands for botan...
Notice: Botan uses many symbols. Look into switching from ld (bfd) to ld (Gold) linker to reduce link times from >15s to <2s
Performing "release" build using /root/dmd2/linux/bin64/dmd for x86_64.
botan-math 1.0.3: building configuration "regular"...
Killed
/root/dmd2/linux/bin64/dmd failed with exit code 137.
root@RegalMusty-VM:~/flint#

如何解决？

**Comment by nametoolong** [comment]
Seems like an OOM. Botan take a lot of memory (~1.5 GiB) when compiling.

**Comment by nametoolong** [comment]
I recommend cross-compiling on a machine with sufficient memory. Flint has bizarre crypto and requires future (mostly compatibility-breaking) changes to be compiled with minimal memory. I am not carrying out any optimization at this moment due to lack of time. PRs are welcome.

**Comment by luckypoem** [comment]
hi.
i get a vps,its ram is 2gb.
but still encounter error:
...
Fetching botan 1.12.9 (getting selected version)...
Running pre-generate commands for botan...
Notice: Botan uses many symbols. Look into switching from ld (bfd) to ld (Gold) linker to reduce link times from >15s to <2s
Performing "release" build using /root/dmd2/linux/bin64/dmd for x86_64.
botan-math 1.0.3: building configuration "regular"...
memutils 0.4.9: building configuration "secure"...
Enhanced memory security is enabled.
Memory debugger enabled
botan 1.12.9: building configuration "full"...
Enhanced memory security is enabled.
Memory debugger enabled
../.dub/packages/botan-1.12.9/botan/source/botan/test.d(80,8): Deprecation: struct std.datetime.StopWatch is deprecated - Use std.datetime.stopwatch.StopWatch.
../.dub/packages/botan-1.12.9/botan/source/botan/test.d(80,8): Deprecation: struct std.datetime.StopWatch is deprecated - Use std.datetime.stopwatch.StopWatch.
../.dub/packages/botan-1.12.9/botan/source/botan/test.d(81,11): Deprecation: struct std.datetime.StopWatch is deprecated - Use std.datetime.stopwatch.StopWatch.
../.dub/packages/botan-1.12.9/botan/source/botan/asn1/ber_dec.d(280,36): Deprecation: integral promotion not done for ~obj.value.opIndex(i), use '-transition=intpromote' switch or ~cast(int)(obj.value.opIndex(i))
../.dub/packages/botan-1.12.9/botan/source/botan/asn1/der_enc.d(219,33): Deprecation: integral promotion not done for ~m_contents.opIndex(i), use '-transition=intpromote' switch or ~cast(int)(m_contents.opIndex(i))
../.dub/packages/botan-1.12.9/botan/source/botan/block/idea.d(84,20): Deprecation: integral promotion not done for -this.m_EK.opIndex(2LU), use '-transition=intpromote' switch or -cast(int)(this.m_EK.opIndex(2LU))
../.dub/packages/botan-1.12.9/botan/source/botan/block/idea.d(85,20): Deprecation: integral promotion not done for -this.m_EK.opIndex(1LU), use '-transition=intpromote' switch or -cast(int)(this.m_EK.opIndex(1LU))
../.dub/packages/botan-1.12.9/botan/source/botan/block/idea.d(93,31): Deprecation: integral promotion not done for -this.m_EK.opIndex(j + 3LU), use '-transition=intpromote' switch or -cast(int)(this.m_EK.opIndex(j + 3LU))
../.dub/packages/botan-1.12.9/botan/source/botan/block/idea.d(94,31): Deprecation: integral promotion not done for -this.m_EK.opIndex(j + 4LU), use '-transition=intpromote' switch or -cast(int)(this.m_EK.opIndex(j + 4LU))
../.dub/packages/botan-1.12.9/botan/source/botan/block/idea.d(101,19): Deprecation: integral promotion not done for -this.m_EK.opIndex(50LU), use '-transition=intpromote' switch or -cast(int)(this.m_EK.opIndex(50LU))
../.dub/packages/botan-1.12.9/botan/source/botan/block/idea.d(102,19): Deprecation: integral promotion not done for -this.m_EK.opIndex(49LU), use '-transition=intpromote' switch or -cast(int)(this.m_EK.opIndex(49LU))
../.dub/packages/botan-1.12.9/botan/source/botan/block/idea.d(127,56): Deprecation: integral promotion not done for ~P_mask, use '-transition=intpromote' switch or ~cast(int)(P_mask)
../.dub/packages/botan-1.12.9/botan/source/botan/block/rc2.d(41,29): Deprecation: integral promotion not done for ~R3, use '-transition=intpromote' switch or ~cast(int)(R3)
../.dub/packages/botan-1.12.9/botan/source/botan/block/rc2.d(44,29): Deprecation: integral promotion not done for ~R0, use '-transition=intpromote' switch or ~cast(int)(R0)
../.dub/packages/botan-1.12.9/botan/source/botan/block/rc2.d(47,29): Deprecation: integral promotion not done for ~R1, use '-transition=intpromote' switch or ~cast(int)(R1)
../.dub/packages/botan-1.12.9/botan/source/botan/block/rc2.d(50,29): Deprecation: integral promotion not done for ~R2, use '-transition=intpromote' switch or ~cast(int)(R2)
../.dub/packages/botan-1.12.9/botan/source/botan/block/rc2.d(84,29): Deprecation: integral promotion not done for ~R2, use '-transition=intpromote' switch or ~cast(int)(R2)
../.dub/packages/botan-1.12.9/botan/source/botan/block/rc2.d(87,29): Deprecation: integral promotion not done for ~R1, use '-transition=intpromote' switch or ~cast(int)(R1)
../.dub/packages/botan-1.12.9/botan/source/botan/block/rc2.d(90,29): Deprecation: integral promotion not done for ~R0, use '-transition=intpromote' switch or ~cast(int)(R0)
../.dub/packages/botan-1.12.9/botan/source/botan/block/rc2.d(93,29): Deprecation: integral promotion not done for ~R3, use '-transition=intpromote' switch or ~cast(int)(R3)
../.dub/packages/botan-1.12.9/botan/source/botan/asn1/der_enc.d(219,33): Deprecation: integral promotion not done for ~m_contents.opIndex(i), use '-transition=intpromote' switch or ~cast(int)(m_contents.opIndex(i))
/root/dmd2/linux/bin64/../../src/druntime/import/object.d(3440,23): Error: template memutils.refcounted.RefCounted!(X509CertificateImpl, ThreadMem).RefCounted.opCast does not match any template declaration
/root/dmd2/linux/bin64/../../src/druntime/import/object.d(3440,49): Error: template memutils.refcounted.RefCounted!(X509CertificateImpl, ThreadMem).RefCounted.opCast does not match any template declaration
/root/dmd2/linux/bin64/../../src/druntime/import/object.d(3441,39): Error: template memutils.refcounted.RefCounted!(X509CertificateImpl, ThreadMem).RefCounted.opCast does not match any template declaration
../.dub/packages/memutils-0.4.9/memutils/source/memutils/vector.d(790,10): Error: template instance object.__equals!(const(RefCounted!(X509CertificateImpl, ThreadMem)), const(RefCounted!(X509CertificateImpl, ThreadMem))) error instantiating
../.dub/packages/memutils-0.4.9/memutils/source/memutils/helpers.d(71,27):        instantiated from here: opEquals!()
../.dub/packages/botan-1.12.9/botan/source/botan/tls/server.d(689,38):        instantiated from here: opEquals!(RefCounted!(Vector!(RefCounted!(X509CertificateImpl, ThreadMem), ThreadMem), ThreadMem))
/root/dmd2/linux/bin64/dmd failed with exit code 1.
root@vps:~/flint#

how to fix it?

root@vps:~/flint# free -m
             total       used       free     shared    buffers     cached
Mem:          2010        645       1364          5         40        512
-/+ buffers/cache:         93       1916
Swap:         2047          0       2047
root@vps:~/flint#

**Comment by nametoolong** [comment]
I've opened an [issue](https://github.com/etcimon/botan/issues/41) in botan. Meanwhile downgrading to DMD 2.074.1 is the easiest way to workaround this.

**Comment by luckypoem** [comment]
seem still not ok:
root@vps:~# dmd --version
DMD64 D Compiler v2.074.1
Copyright (c) 1999-2017 by Digital Mars written by Walter Bright
root@vps:~# cd flint
root@vps:~/flint# dub build --build=release
Running pre-generate commands for botan...
Notice: Botan uses many symbols. Look into switching from ld (bfd) to ld (Gold) linker to reduce link times from >15s to <2s
Performing "release" build using dmd for x86_64.
botan-math 1.0.3: building configuration "regular"...
memutils 0.4.9: building configuration "secure"...
Enhanced memory security is enabled.
Memory debugger enabled
botan 1.12.9: building configuration "full"...
Enhanced memory security is enabled.
Memory debugger enabled

then no reaction at all.why?

**Comment by luckypoem** [comment]
oh ,see ,now it reacts:
root@vps:~/flint# dub build --build=release
Running pre-generate commands for botan...
Notice: Botan uses many symbols. Look into switching from ld (bfd) to ld (Gold) linker to reduce link times from >15s to <2s
Performing "release" build using dmd for x86_64.
botan-math 1.0.3: building configuration "regular"...
memutils 0.4.9: building configuration "secure"...
Enhanced memory security is enabled.
Memory debugger enabled
botan 1.12.9: building configuration "full"...
Enhanced memory security is enabled.
Memory debugger enabled


flint ~master: building configuration "application"...

Enhanced memory security is enabled.
Memory debugger enabled
Linking...
root@vps:~/flint#

**Comment by luckypoem** [comment]
root@vps:~/flint# which flint
root@vps:~/flint#

你说“服务端使用 --config=flint.config_server 启动。” ，不过服务器端的可执行文件是什么？

**Comment by luckypoem** [comment]
oh, i find "flint" exec file in ~/flint/,but 
root@vps:~/flint/keytool# dub --build=release
Running pre-generate commands for botan...
Notice: Botan uses many symbols. Look into switching from ld (bfd) to ld (Gold) linker to reduce link times from >15s to <2s
Performing "release" build using dmd for x86_64.
memutils 0.4.9: target for configuration "secure" is up to date.
botan 1.11.14: building configuration "full"...
../../.dub/packages/botan-1.11.14/botan/source/botan/tls/policy.d(58,13): Deprecation: Implicit string concatenation is deprecated, use "SEED" ~ "3DES" instead
../../.dub/packages/botan-1.11.14/botan/source/botan/utils/asm_x86_32/asm_x86_32.d(138,17): Deprecation: Implicit string concatenation is deprecated, use "\x0a" ~ "jne " instead
../../.dub/packages/botan-1.11.14/botan/source/botan/utils/asm_x86_32/asm_x86_32.d(143,17): Deprecation: Implicit string concatenation is deprecated, use "\x0a" ~ "jge " instead
../../.dub/packages/botan-1.11.14/botan/source/botan/utils/asm_x86_32/asm_x86_32.d(151,17): Deprecation: Implicit string concatenation is deprecated, use "\x0a" ~ "jz " instead
../../.dub/packages/botan-1.11.14/botan/source/botan/utils/asm_x86_32/asm_x86_32.d(156,17): Deprecation: Implicit string concatenation is deprecated, use "\x0a" ~ "jl " instead
../../.dub/packages/botan-1.11.14/botan/source/botan/utils/asm_x86_32/asm_x86_32.d(206,71): Deprecation: Implicit string concatenation is deprecated, use "\x0a" ~ "adcl " instead
../../.dub/packages/botan-1.11.14/botan/source/botan/utils/http_util/http_util.d(29,12): Error: module stream is in file 'std/stream.d' which cannot be read
import path[0] = ../../.dub/packages/botan-1.11.14/botan/source/
import path[1] = ../../.dub/packages/memutils-0.4.9/memutils/source/
import path[2] = /root/dmd2/linux/bin64/../../src/phobos
import path[3] = /root/dmd2/linux/bin64/../../src/druntime/import
dmd failed with exit code 1.
root@vps:~/flint/keytool#

how to fix it?

**Comment by nametoolong** [comment]
Check out the last commit. I forgot to upgrade keytool some time ago.

**Comment by luckypoem** [comment]
不过在mac上，生成flint失败：
...
botan-math 1.0.3: building configuration "regular"...
memutils 0.4.9: building configuration "secure"...
Enhanced memory security is enabled.
Memory debugger enabled
botan 1.12.9: building configuration "full"...
Enhanced memory security is enabled.
Memory debugger enabled
flint ~master: building configuration "application"...
Enhanced memory security is enabled.
Memory debugger enabled
Linking...
ld: in ../.dub/packages/botan-1.12.9/botan/.dub/build/full-release-posix.osx-x86_64-dmd_2074-608D0783CCE7705658A7CDFADF5B505E/libbotan.a(unique_4883_3b6.o), in section __TEXT,__textcoal_nt reloc 0: symbol index out of range for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: linker exited with status 1
dmd failed with exit code 1.
yudeMacBook-Air:flint brite$

怎么解决？

**Comment by luckypoem** [comment]
yudeMacBook-Air:flint brite$ dmd --version
DMD64 D Compiler v2.074.1
Copyright (c) 1999-2017 by Digital Mars written by Walter Bright
yudeMacBook-Air:flint brite$

**Comment by nametoolong** [comment]
Due to [another bug](https://github.com/etcimon/botan/issues/14). Try LDC or GDC. If you encounter any other problem, I will fork botan and push my ugly hacks on. 
I am on the edge of saying f**k to DMD.

**Comment by luckypoem** [comment]
我下载了下载http://downloads.dlang.org/releases/2.x/2.074.1/dmd.2.074.1.dmg，来安装dmd.如何卸载dmd?
我在/applications/里面没发现有dmd的目录。

**Comment by nametoolong** [comment]
OSX 上的 DMD 安装在 `/Library/D/dmd` 下。如果仍然无法卸载，可以手动解压 dmd.2.074.1.dmg 并用 bash 运行其中的 uninstall.command .

**Comment by luckypoem** [comment]
哦，
我删除了/Library/D/dmd/目录。
用brew install ldc安装了ldc,
yudeMacBook-Air:~ brite$ which ldc
yudeMacBook-Air:~ brite$ which ldc2
/usr/local/bin/ldc2
yudeMacBook-Air:~ brite$ which dmd
yudeMacBook-Air:~ brite$ which dub
yudeMacBook-Air:~ brite$

既然没有可执行文件dub了，还怎么运行dub?
"dub build --build=release"就没法运行了:
yudeMacBook-Air:~ brite$ cd flint
yudeMacBook-Air:flint brite$ dub build --build=release
-bash: dub: command not found
yudeMacBook-Air:flint brite$ 

那怎么生成flint?

**Comment by nametoolong** [comment]
`brew install dub`  
如果 brew 安装失败，可以在 https://code.dlang.org/download 下载独立安装包，解压得到的 `dub` 可以直接执行。如果 dub 没有自动找到 ldc，需要 `dub build --build=release --compiler=ldc` 指定编译器。

**Comment by luckypoem** [comment]
dub安装成功了，但是
yudeMacBook-Air:flint brite$ ./flint --config=flint.config
2018-02-08T12:57:35.538:main.d:main:1598 Reading configuration file flint.config
2018-02-08T12:57:35.547:main.d:main:1627 Reading pubkey.key
2018-02-08T12:57:35.548:main.d:doProofOfWork:662 Doing Proof of Work...
2018-02-08T12:57:38.165:main.d:launchClient:711 Connecting...
2018-02-08T12:57:38.406:main.d:handshake:756 Handshaking...
Segmentation fault: 11
yudeMacBook-Air:flint brite$ ps aux|grep flint
yuming          29880   0.0  0.0  2451236    816 s000  S+   12:58下午   0:00.01 grep flint
yudeMacBook-Air:flint brite$
yudeMacBook-Air:flint brite$ cat flint.config
type=client

rotors=II VI V
rings=1 16 7
reflector=B

listen=127.0.0.1
port=4500
remote=my-vps-ip
rport=3967
timeout=20

keyfile=pubkey.key
powleadingzero=2
powfirstbytemax=32
powsalt=what
maxdisconnectdelay=0
yudeMacBook-Air:flint brite$ 

服务器端在运行中：
root@vps:~# ps aux|grep flint
root     24430  0.0  0.4 184432  9100 pts/1    Sl   04:38   0:00 ./flint --config=flint.config_server
root     24772  0.0  0.1  12732  2164 pts/3    R+   06:08   0:00 grep flint
root@vps:~#

客户端怎么根本没在运行中呢？

**Comment by luckypoem** [comment]
yudeMacBook-Air:flint brite$ ls
LICENSE			dub.selections.json	keytool
README.md		flint			pubkey.key
README.zh_cn.md		flint.config		source
dub.json		flint.config_server
yudeMacBook-Air:flint brite$

服务器上：
root@vps:~/flint# ls
dub.json	     flint.config	  LICENSE      README.zh_cn.md
dub.selections.json  flint.config_server  privkey.key  source
flint		     keytool		  README.md
root@vps:~/flint#
root@vps:~/flint# cat flint.config_server
type=server

rotors=II VI V
rings=1 16 7
reflector=B

listen=0.0.0.0
port=3967
remote=127.0.0.1
rport=1080
timeout=20
idletimeout=10

keyfile=privkey.key
powlife=30
powleadingzero=2
powfirstbytemax=32
powsalt=what
maxdisconnectdelay=1000
root@vps:~/flint#

flint.config_server文件里的remote的值和rport的值需要改吗

**Comment by nametoolong** [comment]
需要。Flint 类似于 `kcptun` ，需要把服务端的 `remote` 和 `rport` 指向服务端运行的 HTTP 或 SOCKS 服务器才可以在客户端作为 HTTP 或 SOCKS 代理使用。至于客户端 segfault 的问题又是因为另一个 [bug](https://github.com/etcimon/botan/issues/34)，要通过关闭 `botan-math` 的汇编优化解决：
`botan-math` 的 `dub.json` 中把
```json
		{
			"name": "regular",
			"targetType": "staticLibrary",
			"dflags-windows-x86": [
				"-m32mscoff"
			]
		},
```
改成
```json
		{
			"name": "regular",
			"targetType": "staticLibrary",
			"dflags-windows-x86": [
				"-m32mscoff"
			],
			"dflags-ldc": ["-noasm"]
		},
```

**Comment by luckypoem** [comment]
在~/.dub/里面没有packages啊，
yudeMacBook-Air:.dub brite$ ls
build		dub.json	obj

**Comment by nametoolong** [comment]
`~` 指 HOME 目录，不是当前目录下的 `.dub` .

**Comment by luckypoem** [comment]
yudeMacBook-Air:flint brite$ dub build --build=release-debug --force
Running pre-generate commands for botan...
@(#)PROGRAM:ld  PROJECT:ld64-278.4
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
LTO support using: LLVM version 8.1.0, (clang-802.0.42)
TAPI support using: Apple TAPI version 1.33.11
Notice: Botan uses many symbols. Look into switching from ld (bfd) to ld (Gold) linker to reduce link times from >15s to <2s
Performing "release-debug" build using ldc2 for x86_64.
botan-math 1.0.3: building configuration "regular"...
memutils 0.4.9: building configuration "secure"...
Enhanced memory security is enabled.
Memory debugger enabled
botan 1.12.9: building configuration "full"...
Enhanced memory security is enabled.
Memory debugger enabled
../.dub/packages/botan-1.12.9/botan/source/botan/test.d(80,8): Deprecation: struct std.datetime.StopWatch is deprecated - Use std.datetime.stopwatch.StopWatch.
../.dub/packages/botan-1.12.9/botan/source/botan/test.d(80,8): Deprecation: struct std.datetime.StopWatch is deprecated - Use std.datetime.stopwatch.StopWatch.
../.dub/packages/botan-1.12.9/botan/source/botan/test.d(81,11): Deprecation: struct std.datetime.StopWatch is deprecated - Use std.datetime.stopwatch.StopWatch.
../.dub/packages/botan-1.12.9/botan/source/botan/entropy/hres_timer.d(136,5): Error: static assert  0 is false
ldc2 failed with exit code 1.
yudeMacBook-Air:flint brite$

还是出错

**Comment by nametoolong** [comment]
这个问题需要修改 botan 才能解决。我新建一个分支把修改过的 botan 打包上去。等搞好了再通知你。

**Comment by nametoolong** [comment]
由于另一些问题，打包成单个 package 之后无法编译。如果你还有耐心，可以参考
 https://github.com/etcimon/botan/issues/34#issuecomment-307415862 手动给 `botan-math` 打补丁。

**Comment by luckypoem** [comment]
没看懂那边的内容。怎么打补丁，可以具体说说吗

**Comment by nametoolong** [comment]
需要手动修改 `~/.dub/packages/botan-math-1.0.3/botan-math/source/botan_math/mp_word.d` 中的几个函数（在不同机器上会 segfault 的函数不同），把 `word8_add3` `word8_sub2` `word8_sub3` `word8_linmul2` `word8_linmul3` `word8_madd3` 的汇编代码去掉。详细 diff 在[这里](https://gist.github.com/nametoolong/bc7daae2a342e1239eac5824acb01028).

**Comment by luckypoem** [comment]
眼睛都看花。
可否把你改好的~/.dub/packages/botan-math-1.0.3/botan-math/source/botan_math/mp_word.d文件的内容粘贴在此？
非常感谢。

**Comment by nametoolong** [comment]
把那个 gist 下载下来然后 `patch mp_word.d mp_word.diff` 即可。也可以直接下载 https://gist.github.com/nametoolong/4b5e396ee4fb12a0273caad80b0e3e13 .

**Comment by luckypoem** [comment]
yudeMacBook-Air:flint brite$ ./flint --config=flint.config
2018-02-08T23:06:42.828:main.d:main:1598 Reading configuration file flint.config
2018-02-08T23:06:42.848:main.d:main:1627 Reading pubkey.key
2018-02-08T23:06:42.850:main.d:doProofOfWork:662 Doing Proof of Work...
2018-02-08T23:06:42.938:main.d:launchClient:711 Connecting...
2018-02-08T23:06:43.171:main.d:handshake:756 Handshaking...
2018-02-08T23:06:43.405:main.d:handshake:816 Connection established
2018-02-08T23:06:43.406:main.d:clientMain:845 Listening on 127.0.0.1:4500

这表示ok了吗？

**Comment by nametoolong** [comment]
OK 了，接下来设置应用程序的代理即可。

**Comment by luckypoem** [comment]
服务器上装了个tinyproxy,用做flint的后端。不过翻墙速度很慢，基本打不开youtube

**Comment by luckypoem** [comment]
你很熟悉mac.有什么办法把linux下的可执行文件转换为mac下的可执行文件吗？

**Comment by nametoolong** [comment]
Linux 和 OS X 的 ABI 不同，所以没有办法。因为 flint 是个 TCP in TCP 代理并且把数据编码成可见字符，所以速度相对其他代理来说比较慢。如果 flint 使用的带宽没有达到 VPS 能提供的带宽，使用 BBR 等 TCP 加速方法可以提高速度。

**Comment by nametoolong** [comment]
增大 [source/main.d](../blob/master/source/main.d) 第 66-68 行的 `EDGE_INBUF_SIZE` 和
 `SERVER_OUTBOUND_MESSAGE_SIZE` 也可以提高速度。如果要看 Youtube 的话建议在**服务器端**改成
```
const size_t EDGE_INBUF_SIZE = 4000;

const size_t SERVER_OUTBOUND_MESSAGE_SIZE = 8600;
```
并重新编译，客户端无需修改。不过不建议用这个项目大流量翻墙，因为 flint 的平均流量开销高达 2.4 倍，而且不能隐藏某些特征。这个项目的设计目的是让流量特征看起来不像流量特征，不是隐藏流量特征。

**Comment by luckypoem** [comment]
你这个不是加密连接的吧？我用stunnel+tinyproxy比你这个程序快了很多

**Comment by nametoolong** [comment]
某种程度上说是加密的，但是用的是二战时的密码，目的是抵抗某些复杂的流量分析方法，但是增加了其他方面的特征。详情看 README .

**Comment by luckypoem** [comment]
服务器上的后端改为使用squid3,本地浏览器改为chrome+switchyomega,这样,用chrome，竟然打开了youtube.不过不明白“flint 的平均流量开销高达 2.4 倍”是什么意思？是非常耗流量的意思吗

**Comment by luckypoem** [comment]
不过看youtube,只能看2-3分钟，就会出现“Segmentation fault: 11”错误，看样子跟youtube还是无缘

**Comment by nametoolong** [comment]
对，flint 非常耗流量。OS X 上 segfault 可能还有别的原因，但是手边没有 Mac，调不了。

**Comment by luckypoem** [comment]
服务器端容易退出，可否在以后的版本中，加上--daemon参数的支持？

**Comment by nametoolong** [comment]
可以。

**Comment by nametoolong** [comment]
@luckypoem 由于 DMD 的又一个新 bug，暂时不会支持 run as daemon.

**Comment by luckypoem** [comment]
@nametoolong 
你这个程序访问非youtube网站，还挺快。只是不明白为何一访问youtube网站，客户端就会断开连接呢？
（即出现Segmentation fault: 11错误）

**Comment by luckypoem** [comment]
你这个程序有windows下的客户端吗？可否上传到https://github.com/nametoolong/flint/releases 这里？

**Comment by nametoolong** [comment]
@luckypoem 已发布。

**Comment by luckypoem** [comment]
服务端很容易退出。如何写一段脚本来监控服务端，一旦服务端退出，就自动重启？
你可否写一段这样的脚本？

**Comment by nametoolong** [comment]
建议直接用 screen 来运行，因为 D 语言标准库中的日志模块在 stdout 关闭的时候有时会出现一些问题。

**Comment by luckypoem** [comment]
安装了screen,但一时不会用，能否指导一下具体怎么用？
我的flint目录为/root/flint/, 可执行文件flint在/root/flint/下面。

**Comment by luckypoem** [comment]
root@vps:~/flint# ls
dub.json             flint.config_server  README.md        
dub.selections.json  keytool              README.zh_cn.md  
flint                LICENSE                       source
flint.config         privkey.key       
root@vps:~/flint#

**Comment by nametoolong** [comment]
如果是手动管理，直接在 `screen` 后接需要执行的命令就可以，输入 `Ctrl-a d` 来让 `screen` 进程在后台运行，用 `screen -ls` 列出会话，用 `screen -r` 来恢复会话。如果需要自动化管理，可以这样：
```bash
screen -S flint -d -m -X .\flint # 启动 flint
screen -r flint # 恢复会话
```

**Comment by luckypoem** [comment]
看了这里https://www.ibm.com/developerworks/cn/linux/l-cn-screen/ ，会用screen了。只是不明白
“screen -S flint -d -m -X .\flint ”里的“-d -m -X .\flint”是什么意思？

**Comment by luckypoem** [comment]
服务端没问题了。只是访问某些网站如freefq.com,客户端莫名其妙就崩溃了。你可否搞个mac虚拟机试试？

**Comment by nametoolong** [comment]
可以。

**Comment by luckypoem** [comment]
怎么样，在mac虚拟机里面试了吗

**Comment by luckypoem** [comment]
hello.
换了一台openvz 2gb ram的vps, 在flint目录里，运行dub build --build=release ，未能生成flint可执行文件，上次是在kvm 2gb ram的vps上编译成功的，可见在openvz 2gb ram的vps上也未必能编译成功。所以麻烦你上传linux vps(64位）版的flint可执行文件到https://github.com/nametoolong/flint/releases ,
tks
